version: "3.9"

services:
  frontend:
    build:
      context: .
      target: production
      args:
        NUXT_PUBLIC_API_BASE: http://localhost:8000/api/v1
        NUXT_PUBLIC_MEDIA_BASE: http://localhost:8000
    restart: unless-stopped
    environment:
      NUXT_PUBLIC_API_BASE: http://backend:8000/api/v1
      NUXT_PUBLIC_MEDIA_BASE: http://localhost:8000
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "3000:3000"
